Repository FootMark-Archive/FootMark-iOS, pull requests merged in 2024-06, with the labels that each got.

#16 [Feat] - 로그인 View 및 기능 구현 완료 (#4)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FootMark/FootMark/Application/AppDelegate.swift
  FootMark/FootMark/Application/Info.plist
  FootMark/FootMark/Application/SceneDelegate.swift
  FootMark/FootMark/FootMark.entitlements
  FootMark/FootMark/GoogleService-Info.plist
  FootMark/FootMark/Network/API/API.swift
  FootMark/FootMark/Network/Base/BaseService.swift
  FootMark/FootMark/Network/Base/BaseTargetType.swift
  FootMark/FootMark/Network/Base/MoyaLoggingPlugin.swift
  FootMark/FootMark/Network/Base/NetworkResults.swift
  FootMark/FootMark/Network/Base/NetworkService.swift
  FootMark/FootMark/Network/Config/Config.swift
  FootMark/FootMark/Network/DTO/DTO.swift
  FootMark/FootMark/Network/DTO/LoginDTO/Request/LoginRequestModel.swift
  FootMark/FootMark/Network/DTO/LoginDTO/Response/LoginDTO.swift
  FootMark/FootMark/Network/Foundation/AFLogger.swift
  FootMark/FootMark/Network/Foundation/BaseAPI.swift
  FootMark/FootMark/Network/Foundation/BaseResponse.swift
  FootMark/FootMark/Network/Foundation/BaseTargetType.swift
  FootMark/FootMark/Network/Foundation/ImageUploader.swift
  FootMark/FootMark/Network/Foundation/NetworkResult.swift
  FootMark/FootMark/Network/Foundation/URLConst.swift
  FootMark/FootMark/Network/Login/LoginService.swift
  FootMark/FootMark/Network/Login/LoginTargetType.swift
  FootMark/FootMark/Network/Router/BaseRouter/BaseRouter.swift
  FootMark/FootMark/Presentation/Base/ViewController/BaseViewController.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
  FootMark/FootMark/Presentation/Sign/View/LoginView.swift
  FootMark/FootMark/Presentation/Sign/ViewController/LoginViewController.swift
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Black1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Blue1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/White1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@1x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo2.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo2.imageset/Logo.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/apple_SignInButton.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/apple_SignInButton.imageset/apple_SignInButton.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton 1.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton 2.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton.png
  FootMark/FootMark/Resource/Font/Font.swift
  FootMark/FootMark/Resource/Font/Viga-Regular.ttf
  FootMark/FootMark/Util/Extension/UIColor++.swift
  FootMark/FootMark/Util/Extension/UISegmented++.swift
  FootMark/FootMark/Util/NameSpace/Image.swift
Labels: ✨ Feature, 📬 API, 🍙 신영 🍙

#19 [Fix] - pbxproj 파일의 충돌 오류 해결 완료 (#18)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FootMark/FootMark/Application/AppDelegate.swift
  FootMark/FootMark/Application/Info.plist
  FootMark/FootMark/Application/SceneDelegate.swift
  FootMark/FootMark/FootMark.entitlements
  FootMark/FootMark/GoogleService-Info.plist
  FootMark/FootMark/Network/API/API.swift
  FootMark/FootMark/Network/Base/BaseService.swift
  FootMark/FootMark/Network/Base/BaseTargetType.swift
  FootMark/FootMark/Network/Base/MoyaLoggingPlugin.swift
  FootMark/FootMark/Network/Base/NetworkResults.swift
  FootMark/FootMark/Network/Base/NetworkService.swift
  FootMark/FootMark/Network/Config/Config.swift
  FootMark/FootMark/Network/DTO/DTO.swift
  FootMark/FootMark/Network/DTO/LoginDTO/Request/LoginRequestModel.swift
  FootMark/FootMark/Network/DTO/LoginDTO/Response/LoginDTO.swift
  FootMark/FootMark/Network/Foundation/AFLogger.swift
  FootMark/FootMark/Network/Foundation/BaseAPI.swift
  FootMark/FootMark/Network/Foundation/BaseResponse.swift
  FootMark/FootMark/Network/Foundation/BaseTargetType.swift
  FootMark/FootMark/Network/Foundation/ImageUploader.swift
  FootMark/FootMark/Network/Foundation/NetworkResult.swift
  FootMark/FootMark/Network/Foundation/URLConst.swift
  FootMark/FootMark/Network/Login/LoginService.swift
  FootMark/FootMark/Network/Login/LoginTargetType.swift
  FootMark/FootMark/Network/Router/BaseRouter/BaseRouter.swift
  FootMark/FootMark/Presentation/Base/ViewController/BaseViewController.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
  FootMark/FootMark/Presentation/Sign/View/LoginView.swift
  FootMark/FootMark/Presentation/Sign/ViewController/LoginViewController.swift
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Black1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Blue1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/White1.colorset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@1x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo.imageset/SWLogo@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo2.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/SWLogo2.imageset/Logo.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/apple_SignInButton.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/apple_SignInButton.imageset/apple_SignInButton.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton 1.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton 2.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/google_SignInButton.imageset/google_SignInButton.png
  FootMark/FootMark/Resource/Font/Font.swift
  FootMark/FootMark/Resource/Font/Viga-Regular.ttf
  FootMark/FootMark/Util/Extension/UIColor++.swift
  FootMark/FootMark/Util/Extension/UISegmented++.swift
  FootMark/FootMark/Util/NameSpace/Image.swift
Labels: 🐞 BugFix, 🍙 신영 🍙

#21 [Fix] 사이드바 통합 구현 (#20)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark/Presentation/Sidebar/Model/SidebarModel.swift
  FootMark/FootMark/Presentation/Sidebar/View/SidebarView.swift
  FootMark/FootMark/Presentation/Sidebar/View/SidebarViewCell.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/MainContentViewController.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/SidebarViewController.swift
  FootMark/FootMark/Util/Extension/UIImage++.swift
Labels: 🐞 BugFix, 🍎 성은 🍎

#23 [Fix] - 프로필 통합 구현 (#22)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark/Presentation/Profile/View/ProfileView.swift
  FootMark/FootMark/Presentation/Profile/ViewController/ProfileImageViewController.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/ProfileViewController.swift
  FootMark/FootMark/Util/Extension/UIImage++.swift
Labels: 🐞 BugFix, ✨ Feature, 🍎 성은 🍎

#26 [Style] - 일기뷰 디자인(#25)
  FootMark/FootMark/Presentation/Diary/View/DiaryView.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Colors/White2.colorset/Contents.json
Labels: 🎨 Style, 🍎 성은 🍎

#28 [API] - Moya AccessToken 헤더 추가 방법 및 Emoji 파트 예시 완료 (#27)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark/Network/Base/NetworkService.swift
  FootMark/FootMark/Network/DTO/EmojiDTO/Request/PostEmojiRequestModel.swift
  FootMark/FootMark/Network/DTO/EmojiDTO/Response/PostEmojiDTO.swift
  FootMark/FootMark/Network/Emoji/EmojiService.swift
  FootMark/FootMark/Network/Emoji/EmojiTargetType.swift
  FootMark/FootMark/Presentation/Sign/ViewController/LoginViewController.swift
Labels: ✨ Feature, 📬 API, 🍙 신영 🍙

#31 [Del] #30 - 파일 정리
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark/Application/SceneDelegate.swift
  FootMark/FootMark/Presentation/Diary/View/AddDiaryView.swift
  FootMark/FootMark/Presentation/Diary/View/DiaryView.swift
  FootMark/FootMark/Presentation/Diary/ViewController/AddDiaryViewController.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
  FootMark/FootMark/Presentation/Profile/View/ProfileView.swift
  FootMark/FootMark/Presentation/Profile/ViewController/ProfileImageViewController.swift
  FootMark/FootMark/Presentation/Sidebar/Model/SidebarModel.swift
  FootMark/FootMark/Presentation/Sidebar/View/SidebarView.swift
  FootMark/FootMark/Presentation/Sidebar/View/SidebarViewCell.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/MainContentViewController.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/SidebarViewController.swift
Labels: 🍎 성은 🍎

#34 [Feat] - 월별 몰아보기 뷰 구현 완료 (#14)
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  FootMark/FootMark/Network/Login/LoginTargetType.swift
  FootMark/FootMark/Presentation/Base/View/BaseView.swift
  FootMark/FootMark/Presentation/Base/ViewController/BaseViewController.swift
  FootMark/FootMark/Presentation/MonthlyReview/View/MonthlyReviewView.swift
  FootMark/FootMark/Presentation/MonthlyReview/View/TabView.swift
  FootMark/FootMark/Presentation/MonthlyReview/ViewController/CustomNavigationController.swift
  FootMark/FootMark/Presentation/MonthlyReview/ViewController/MonthlyReviewViewController.swift
  FootMark/FootMark/Presentation/Sign/View/LoginView.swift
  FootMark/FootMark/Presentation/Sign/ViewController/LoginViewController.swift
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/BackBtn.imageset/BackBtn.svg
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/BackBtn.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyBestHappy_bf.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyBestHappy_bf.imageset/iPhone 14 & 15 Pro - 3.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyBestHappy_bf.imageset/iPhone 14 & 15 Pro - 3@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyBestHappy_bf.imageset/iPhone 14 & 15 Pro - 3@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyEX_bf.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyEX_bf.imageset/iPhone 14 & 15 Pro - 4.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyEX_bf.imageset/iPhone 14 & 15 Pro - 4@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyEX_bf.imageset/iPhone 14 & 15 Pro - 4@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyMayTotal.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyMayTotal.imageset/iPhone 14 & 15 Pro - 1.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyMayTotal.imageset/iPhone 14 & 15 Pro - 1@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyMayTotal.imageset/iPhone 14 & 15 Pro - 1@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyThanks_bf.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyThanks_bf.imageset/thanks.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyThanks_bf.imageset/thanks@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyThanks_bf.imageset/thanks@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyTotal_bf.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyTotal_bf.imageset/iPhone 14 & 15 Pro - 1.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyTotal_bf.imageset/iPhone 14 & 15 Pro - 1@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/MonthlyTotal_bf.imageset/iPhone 14 & 15 Pro - 1@3x.png
  FootMark/FootMark/Util/Extension/ScrollFitable.swift
Labels: 🐞 BugFix, ✨ Feature, 🍙 신영 🍙

#37 [Feat] - 파일 생성 및 수정
  FootMark/FootMark.xcodeproj/project.pbxproj
  FootMark/FootMark/Network/Base/KeychainManager.swift
  FootMark/FootMark/Network/Base/NetworkService.swift
  FootMark/FootMark/Network/DTO/EmojiDTO/Request/PutEmojiRequestModel.swift
  FootMark/FootMark/Network/DTO/EmojiDTO/Response/PutEmojiDTO.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PostReviewBestRequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PostReviewGoal1RequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PostReviewGoal2RequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PostReviewRequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PostReviewThankfulRequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Request/PutReviewRequestModel.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Response/DelReviewDTO.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Response/PostReviewDTO.swift
  FootMark/FootMark/Network/DTO/ReviewDTO/Response/PutReviewDTO.swift
  FootMark/FootMark/Network/DTO/TodoDTO/Response/GetTodoDTO.swift
  FootMark/FootMark/Network/Emoji/EmojiService.swift
  FootMark/FootMark/Network/Emoji/EmojiTargetType.swift
  FootMark/FootMark/Network/Review/ReviewService.swift
  FootMark/FootMark/Network/Review/ReviewTargetType.swift
  FootMark/FootMark/Network/Todo/TodoService.swift
  FootMark/FootMark/Network/Todo/TodoTargetType.swift
  FootMark/FootMark/Presentation/Diary/View/AddDiaryView.swift
  FootMark/FootMark/Presentation/Diary/View/DiaryView.swift
  FootMark/FootMark/Presentation/Diary/ViewController/AddDiaryViewController.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
Labels: ✨ Feature, 📬 API, 🍎 성은 🍎

#38 Feat/#14
  FootMark/FootMark/Presentation/Diary/View/DiaryView.swift
  FootMark/FootMark/Presentation/Diary/ViewController/AddDiaryViewController.swift
  FootMark/FootMark/Presentation/Diary/ViewController/DiaryViewController.swift
  FootMark/FootMark/Presentation/Main/ViewController/CategoryViewController.swift
  FootMark/FootMark/Presentation/Main/ViewController/MainViewController.swift
  FootMark/FootMark/Presentation/MonthlyReview/ViewController/MonthlyReviewViewController.swift
  FootMark/FootMark/Presentation/Sidebar/ViewController/ProfileViewController.swift
  FootMark/FootMark/Presentation/Sign/ViewController/LoginViewController.swift
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swAllMonthly.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swAllMonthly.imageset/iPhone 14 & 15 Pro - 1.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swAllMonthly.imageset/iPhone 14 & 15 Pro - 1@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swAllMonthly.imageset/iPhone 14 & 15 Pro - 1@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swBestMonthly.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swBestMonthly.imageset/iPhone 14 & 15 Pro - 3.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swBestMonthly.imageset/iPhone 14 & 15 Pro - 3@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swBestMonthly.imageset/iPhone 14 & 15 Pro - 3@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swHealthMonthly.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swHealthMonthly.imageset/iPhone 14 & 15 Pro - 4.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swHealthMonthly.imageset/iPhone 14 & 15 Pro - 4@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swHealthMonthly.imageset/iPhone 14 & 15 Pro - 4@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swStudyMonthly.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swStudyMonthly.imageset/iPhone 14 & 15 Pro - 6.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swStudyMonthly.imageset/iPhone 14 & 15 Pro - 6@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swStudyMonthly.imageset/iPhone 14 & 15 Pro - 6@3x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swThanksMonthly.imageset/Contents.json
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swThanksMonthly.imageset/thanks.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swThanksMonthly.imageset/thanks@2x.png
  FootMark/FootMark/Resource/AssetsCatalog/Assets.xcassets/Images/swThanksMonthly.imageset/thanks@3x.png
  FootMark/FootMark/Util/Extension/UICheckBox++.swift
Labels: 🐞 BugFix, ✨ Feature, 📬 API, 🍙 신영 🍙
